In [6]:
a = 'kamal'
a = "___".join(a)
len(a)
print(a)

k___a___m___a___l


In [7]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[5,6,9],[9,3,1],[4,3,2]]])
print(arr.ndim)
arr

3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[5, 6, 9],
        [9, 3, 1],
        [4, 3, 2]]])

In [33]:
array2=np.array([[1,2,3,4],[5,6,7,8]], dtype=float)
array2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [8]:
arr1 = np.random.randn(2,3)
print(arr1)
#print(arr1.max())
print(arr1.shape)
print(arr1.min())
print(arr1.mean())
print(arr1.ndim)
print(arr1.size)

[[-1.3784647   0.31531896  0.0236483 ]
 [ 0.34642209  0.57667193  0.7022388 ]]
(2, 3)
-1.3784647025134396
0.09763922941867124
2
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

In [34]:
arr = np.array([1, 2, 3, 4], ndmin=3)
print(arr)
print('number of dimensions :', arr.ndim)


[[[1 2 3 4]]]
number of dimensions : 3


In [35]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
x=np.ones((4,5))
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
x=np.full((4,9),5)
print(x)

[[5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]


In [43]:
x=np.random.random((3,4))
print(x)


[[0.3785901  0.4728283  0.20512208 0.56396154]
 [0.45336142 0.13074545 0.90909349 0.93032574]
 [0.13035052 0.69278862 0.09019127 0.32117755]]


In [45]:
x=np.random.randint(10,100,(3,4))
print(x)


[[55 39 14 91]
 [27 79 96 14]
 [73 84 78 37]]


In [65]:
x=np.random.randint(3,16,(1,2,3))
print(x)

[[[ 3 14 12]
  [ 9 10  8]]]


In [77]:
list1=[10,20,30,40,50]
array1=np.array(list1)
type(array1)
array1.size


5

In [86]:
x=np.linspace(7,35,5)
print(x)


[ 7. 14. 21. 28. 35.]


In [87]:
Y, X = np.mgrid[-3:3:100j, -3:3:100j]


In [ ]:
list1=[10,20,30,40,50]
array1=np.asarray(list1)
print(array1)
type(array1)

In [ ]:
x=np.random.randint(10,99,(4,5))
print(x)
print("Shape of the array:\n ",x.shape)
list1 = [x.ndim, x.size, x.dtype]
list2 = [x.max(), x.min(), x.mean(), x.argmax(), x.argmin()]
ar1= np.asarray(list1)
ar2= np.asarray(list2)
print(ar1)
print(ar2)
'''print(list1)
print(list2)'''


In [ ]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
'''print(a)
print(b)'''
#c = np.add(a,b)
x = a+b
x


In [ ]:
arr=np.random.randint(0,365,(4,3))
arr
np.sqrt(arr)
np.sin(arr)
np.cos(arr)
np.log(arr)
arr
arr.argmax()
arr.std()
arr.var()

In [ ]:
arr=np.random.randint(1,10,(3,5))
print(arr)
'''print("---------------")
print(arr.sum(axis=0))
print("---------------")
print(arr.sum(axis=1))
print("---------------")
print(arr.shape)
print("---------------")
print(arr.size)
print("---------------")
print(np.transpose(arr))
print("---------------")
print(arr.reshape(5,3))'''
arr[0,1]

In [ ]:
x = np.array([[3,4],[1,9]],ndmin = 4)
x

In [ ]:
arr_2d=np.random.randint(0,1000,(3,5))
print(arr_2d,arr_2d.size)
arr_2d[arr_2d<50]
b = arr_2d < 653
b
